"""add volume and outcome_prices to markets

Revision ID: fd8bcffb750b
Revises: 362272118057
Create Date: 2026-02-09 20:39:56.225032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd8bcffb750b'
down_revision: Union[str, Sequence[str], None] = '362272118057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('volume', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('markets', sa.Column('outcome_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'outcome_prices')
    op.drop_column('markets', 'volume')
    # ### end Alembic commands ###
